# Generated by Django 2.2 on 2019-05-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userobjects',
        ),
        migrations.DeleteModel(
            name='Wishlistobjects',
        ),
    ]
